// Code generated by Slice Machine. DO NOT EDIT.

import About from './About/index.svelte';
import Banner from './Banner/index.svelte';
import Contact from './Contact/index.svelte';
import Events from './Events/index.svelte';
import Gallery from './Gallery/index.svelte';

export const components = {
	about: About,
	banner: Banner,
	contact: Contact,
	events: Events,
	gallery: Gallery
};
