// Code generated by Slice Machine. DO NOT EDIT.

import About from './About/index.svelte';
import Banner from './Banner/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	about: About,
	banner: Banner,
	rich_text: RichText
};
