// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *beer menu → Item*
 */
export interface BeerMenuDocumentDataItemItem {
	/**
	 * Label field in *beer menu → Item*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: beer_menu.item[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * Beer Color field in *beer menu → Item*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: beer_menu.item[].beer_color
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	beer_color: prismic.ColorField;

	/**
	 * Beer Description field in *beer menu → Item*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: beer_menu.item[].beer_description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	beer_description: prismic.KeyTextField;

	/**
	 * Price Glass field in *beer menu → Item*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: beer_menu.item[].price_glass
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	price_glass: prismic.NumberField;

	/**
	 * Price Pint field in *beer menu → Item*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: beer_menu.item[].price_pint
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	price_pint: prismic.NumberField;

	/**
	 * Price Pitcher field in *beer menu → Item*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: beer_menu.item[].price_pitcher
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	price_pitcher: prismic.NumberField;

	/**
	 * Out of stock field in *beer menu → Item*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: beer_menu.item[].out_of_stock
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	out_of_stock: prismic.BooleanField;
}

/**
 * Content for beer menu documents
 */
interface BeerMenuDocumentData {
	/**
	 * Title field in *beer menu*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: beer_menu.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Image field in *beer menu*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: beer_menu.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Item field in *beer menu*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: beer_menu.item[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	item: prismic.GroupField<Simplify<BeerMenuDocumentDataItemItem>>;
}

/**
 * beer menu document from Prismic
 *
 * - **API ID**: `beer_menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BeerMenuDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<BeerMenuDocumentData>,
	'beer_menu',
	Lang
>;

/**
 * Item in *cocktail menu → Item*
 */
export interface CocktailMenuDocumentDataItemItem {
	/**
	 * soft field in *cocktail menu → Item*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: cocktail_menu.item[].soft
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	soft: prismic.BooleanField;

	/**
	 * Label field in *cocktail menu → Item*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cocktail_menu.item[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * Ingredients field in *cocktail menu → Item*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cocktail_menu.item[].ingredients
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	ingredients: prismic.KeyTextField;

	/**
	 * Price field in *cocktail menu → Item*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cocktail_menu.item[].price
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	price: prismic.NumberField;

	/**
	 * Price Pitcher field in *cocktail menu → Item*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cocktail_menu.item[].price_pitcher
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	price_pitcher: prismic.NumberField;

	/**
	 * Flavor Type field in *cocktail menu → Item*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cocktail_menu.item[].flavor_type
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	flavor_type: prismic.ContentRelationshipField<'flavour_styles'>;

	/**
	 * Out of stock field in *cocktail menu → Item*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: cocktail_menu.item[].out_of_stock
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	out_of_stock: prismic.BooleanField;
}

/**
 * Content for cocktail menu documents
 */
interface CocktailMenuDocumentData {
	/**
	 * Title field in *cocktail menu*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cocktail_menu.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Image field in *cocktail menu*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cocktail_menu.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Item field in *cocktail menu*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cocktail_menu.item[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	item: prismic.GroupField<Simplify<CocktailMenuDocumentDataItemItem>>;
}

/**
 * cocktail menu document from Prismic
 *
 * - **API ID**: `cocktail_menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CocktailMenuDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<CocktailMenuDocumentData>,
	'cocktail_menu',
	Lang
>;

/**
 * Content for dietary badges documents
 */
interface DietaryBadgesDocumentData {
	/**
	 * Label field in *dietary badges*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: dietary_badges.label
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * icon field in *dietary badges*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: dietary_badges.icon
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	icon: prismic.ImageField<never>;
}

/**
 * dietary badges document from Prismic
 *
 * - **API ID**: `dietary_badges`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DietaryBadgesDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<DietaryBadgesDocumentData>,
	'dietary_badges',
	Lang
>;

/**
 * Content for error page documents
 */
interface ErrorPageDocumentData {
	/**
	 * 404 field in *error page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: error_page.404
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	'404': prismic.KeyTextField;

	/**
	 * 505 field in *error page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: error_page.505
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	'505': prismic.KeyTextField;

	/**
	 * Back Home field in *error page*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: error_page.back_home
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	back_home: prismic.LinkField /**
	 * Meta_Title field in *error page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: error_page.meta_title
	 * - **Tab**: Meta
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;
}

/**
 * error page document from Prismic
 *
 * - **API ID**: `error_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ErrorPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<ErrorPageDocumentData>,
	'error_page',
	Lang
>;

/**
 * Content for flavour styles documents
 */
interface FlavourStylesDocumentData {
	/**
	 * Title field in *flavour styles*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: flavour_styles.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *flavour styles*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: flavour_styles.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;

	/**
	 * Color field in *flavour styles*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: flavour_styles.color
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	color: prismic.ColorField;
}

/**
 * flavour styles document from Prismic
 *
 * - **API ID**: `flavour_styles`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FlavourStylesDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<FlavourStylesDocumentData>,
	'flavour_styles',
	Lang
>;

/**
 * Item in *food menu → Item*
 */
export interface FoodMenuDocumentDataItemItem {
	/**
	 * Appetizer field in *food menu → Item*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: food_menu.item[].appetizer
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	appetizer: prismic.BooleanField;

	/**
	 * Label field in *food menu → Item*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: food_menu.item[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * Ingredients field in *food menu → Item*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: food_menu.item[].ingredients
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	ingredients: prismic.KeyTextField;

	/**
	 * Price field in *food menu → Item*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: food_menu.item[].price
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	price: prismic.NumberField;

	/**
	 * Price Variant field in *food menu → Item*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: food_menu.item[].price_variant
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	price_variant: prismic.NumberField;

	/**
	 * Price Variant 2 field in *food menu → Item*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: food_menu.item[].price_variant_2
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	price_variant_2: prismic.NumberField;

	/**
	 * Vegan field in *food menu → Item*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: food_menu.item[].vegan
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	vegan: prismic.BooleanField;

	/**
	 * Vegetarian field in *food menu → Item*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: food_menu.item[].vegetarian
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	vegetarian: prismic.BooleanField;

	/**
	 * Spicy field in *food menu → Item*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: food_menu.item[].spicy
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	spicy: prismic.BooleanField;

	/**
	 * Out of stock field in *food menu → Item*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: food_menu.item[].out_of_stock
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	out_of_stock: prismic.BooleanField;
}

/**
 * Content for food menu documents
 */
interface FoodMenuDocumentData {
	/**
	 * Title field in *food menu*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: food_menu.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Image field in *food menu*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: food_menu.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Item field in *food menu*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: food_menu.item[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	item: prismic.GroupField<Simplify<FoodMenuDocumentDataItemItem>>;
}

/**
 * food menu document from Prismic
 *
 * - **API ID**: `food_menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FoodMenuDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<FoodMenuDocumentData>,
	'food_menu',
	Lang
>;

/**
 * Content for footer documents
 */
interface FooterDocumentData {
	/**
	 * Policy field in *footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: All rights reserved
	 * - **API ID Path**: footer.policy
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	policy: prismic.KeyTextField;

	/**
	 * Logo field in *footer*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>;
}

/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<FooterDocumentData>,
	'footer',
	Lang
>;

/**
 * Item in *form Errors → Name*
 */
export interface FormerrorsDocumentDataNameItem {
	/**
	 * Required field in *form Errors → Name*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.name[].required
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	required: prismic.KeyTextField;

	/**
	 * Minimum field in *form Errors → Name*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.name[].minimum
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	minimum: prismic.KeyTextField;
}

/**
 * Item in *form Errors → Email*
 */
export interface FormerrorsDocumentDataEmailItem {
	/**
	 * Required field in *form Errors → Email*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.email[].required
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	required: prismic.KeyTextField;

	/**
	 * Invalid field in *form Errors → Email*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.email[].invalid
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	invalid: prismic.KeyTextField;
}

/**
 * Item in *form Errors → Phone*
 */
export interface FormerrorsDocumentDataPhoneItem {
	/**
	 * Required field in *form Errors → Phone*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.phone[].required
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	required: prismic.KeyTextField;

	/**
	 * Minimum field in *form Errors → Phone*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.phone[].minimum
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	minimum: prismic.KeyTextField;
}

/**
 * Item in *form Errors → Subject*
 */
export interface FormerrorsDocumentDataSubjectItem {
	/**
	 * Required field in *form Errors → Subject*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.subject[].required
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	required: prismic.KeyTextField;
}

/**
 * Item in *form Errors → Message*
 */
export interface FormerrorsDocumentDataMessageItem {
	/**
	 * Required field in *form Errors → Message*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.message[].required
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	required: prismic.KeyTextField;

	/**
	 * Minimum field in *form Errors → Message*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.message[].minimum
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	minimum: prismic.KeyTextField;
}

/**
 * Item in *form Errors → Date*
 */
export interface FormerrorsDocumentDataDateItem {
	/**
	 * Required_date field in *form Errors → Date*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.date[].required_date
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	required_date: prismic.KeyTextField;

	/**
	 * Required_time field in *form Errors → Date*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.date[].required_time
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	required_time: prismic.KeyTextField;
}

/**
 * Item in *form Errors → reservationType*
 */
export interface FormerrorsDocumentDataReservationtypeItem {
	/**
	 * Required field in *form Errors → reservationType*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.reservationtype[].required
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	required: prismic.KeyTextField;
}

/**
 * Item in *form Errors → NumberOfPeople*
 */
export interface FormerrorsDocumentDataNumberofpeopleItem {
	/**
	 * Required field in *form Errors → NumberOfPeople*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.numberofpeople[].required
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	required: prismic.KeyTextField;
}

/**
 * Content for form Errors documents
 */
interface FormerrorsDocumentData {
	/**
	 * Name field in *form Errors*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.name[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	name: prismic.GroupField<Simplify<FormerrorsDocumentDataNameItem>>;

	/**
	 * Email field in *form Errors*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.email[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	email: prismic.GroupField<Simplify<FormerrorsDocumentDataEmailItem>>;

	/**
	 * Phone field in *form Errors*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.phone[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	phone: prismic.GroupField<Simplify<FormerrorsDocumentDataPhoneItem>>;

	/**
	 * Subject field in *form Errors*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.subject[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	subject: prismic.GroupField<Simplify<FormerrorsDocumentDataSubjectItem>>;

	/**
	 * Message field in *form Errors*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.message[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	message: prismic.GroupField<Simplify<FormerrorsDocumentDataMessageItem>>;

	/**
	 * Date field in *form Errors*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.date[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	date: prismic.GroupField<Simplify<FormerrorsDocumentDataDateItem>>;

	/**
	 * reservationType field in *form Errors*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.reservationtype[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	reservationtype: prismic.GroupField<Simplify<FormerrorsDocumentDataReservationtypeItem>>;

	/**
	 * NumberOfPeople field in *form Errors*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: formerrors.numberofpeople[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	numberofpeople: prismic.GroupField<Simplify<FormerrorsDocumentDataNumberofpeopleItem>>;
}

/**
 * form Errors document from Prismic
 *
 * - **API ID**: `formerrors`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FormerrorsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<FormerrorsDocumentData>,
	'formerrors',
	Lang
>;

/**
 * Item in *nav → Link*
 */
export interface NavDocumentDataLinkItem {
	/**
	 * Label field in *nav → Link*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.link[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * Link field in *nav → Link*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.link[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Content for nav documents
 */
interface NavDocumentData {
	/**
	 * Logo field in *nav*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>;

	/**
	 * Link field in *nav*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.link[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	link: prismic.GroupField<Simplify<NavDocumentDataLinkItem>>;
}

/**
 * nav document from Prismic
 *
 * - **API ID**: `nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<NavDocumentData>,
	'nav',
	Lang
>;

/**
 * Item in *opening Hours → Day*
 */
export interface OpeningHoursDocumentDataDayItem {
	/**
	 * Title field in *opening Hours → Day*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Monday
	 * - **API ID Path**: opening_hours.day[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Hours field in *opening Hours → Day*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 11h00 - 2h00
	 * - **API ID Path**: opening_hours.day[].hours
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hours: prismic.KeyTextField;
}

/**
 * Content for opening Hours documents
 */
interface OpeningHoursDocumentData {
	/**
	 * Title field in *opening Hours*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: opening_hours.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Day field in *opening Hours*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: opening_hours.day[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	day: prismic.GroupField<Simplify<OpeningHoursDocumentDataDayItem>>;
}

/**
 * opening Hours document from Prismic
 *
 * - **API ID**: `opening_hours`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OpeningHoursDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<OpeningHoursDocumentData>,
	'opening_hours',
	Lang
>;

type PageDocumentDataSlicesSlice =
	| MenuSlice
	| MenuBannerSlice
	| EventsSlice
	| ContactSlice
	| GallerySlice
	| AboutSlice
	| BannerSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

/**
 * Item in *settings → Social Media*
 */
export interface SettingsDocumentDataSocialMediaItem {
	/**
	 * Icon field in *settings → Social Media*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.social_media[].icon
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	icon: prismic.KeyTextField;

	/**
	 * Link field in *settings → Social Media*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.social_media[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Item in *settings → CC emails*
 */
export interface SettingsDocumentDataCcEmailsItem {
	/**
	 * CC email field in *settings → CC emails*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.cc_emails[].cc_email
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cc_email: prismic.KeyTextField;
}

/**
 * Item in *settings → OpeningHours*
 */
export interface SettingsDocumentDataOpeningHoursItem {
	/**
	 * DaysHours field in *settings → OpeningHours*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.opening_hours[].dayshours
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	dayshours: prismic.KeyTextField;
}

/**
 * Content for settings documents
 */
interface SettingsDocumentData {
	/**
	 * Business Name field in *settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.business_name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	business_name: prismic.KeyTextField;

	/**
	 * Email field in *settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.email
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	email: prismic.KeyTextField;

	/**
	 * Address field in *settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.address
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	address: prismic.KeyTextField;

	/**
	 * Phone field in *settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.phone
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	phone: prismic.KeyTextField;

	/**
	 * Website field in *settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.website
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	website: prismic.KeyTextField;

	/**
	 * Location field in *settings*
	 *
	 * - **Field Type**: GeoPoint
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.location
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#geopoint
	 */
	location: prismic.GeoPointField;

	/**
	 * Google Maps Api Key field in *settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.google_maps_api_key
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	google_maps_api_key: prismic.KeyTextField;

	/**
	 * Social Media field in *settings*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.social_media[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	social_media: prismic.GroupField<Simplify<SettingsDocumentDataSocialMediaItem>>;

	/**
	 * Root Link field in *settings*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.root_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	root_link: prismic.LinkField;

	/**
	 * CC emails field in *settings*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.cc_emails[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	cc_emails: prismic.GroupField<Simplify<SettingsDocumentDataCcEmailsItem>> /**
	 * Food Type field in *settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.food_type
	 * - **Tab**: Meta
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	food_type: prismic.KeyTextField;

	/**
	 * addressLocality field in *settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.addresslocality
	 * - **Tab**: Meta
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	addresslocality: prismic.KeyTextField;

	/**
	 * adressRegion field in *settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.adressregion
	 * - **Tab**: Meta
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	adressregion: prismic.KeyTextField;

	/**
	 * PostalCode field in *settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.postalcode
	 * - **Tab**: Meta
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	postalcode: prismic.KeyTextField;

	/**
	 * StreetAdress field in *settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.streetadress
	 * - **Tab**: Meta
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	streetadress: prismic.KeyTextField;

	/**
	 * OpeningHours field in *settings*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.opening_hours[]
	 * - **Tab**: Meta
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	opening_hours: prismic.GroupField<Simplify<SettingsDocumentDataOpeningHoursItem>>;
}

/**
 * settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<SettingsDocumentData>,
	'settings',
	Lang
>;

/**
 * Item in *special menu → Item*
 */
export interface SpecialMenuDocumentDataItemItem {
	/**
	 * Title field in *special menu → Item*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: special_menu.item[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *special menu → Item*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: special_menu.item[].description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;

	/**
	 * Poster field in *special menu → Item*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: special_menu.item[].poster
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	poster: prismic.ImageField<never>;
}

/**
 * Content for special menu documents
 */
interface SpecialMenuDocumentData {
	/**
	 * Title field in *special menu*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: special_menu.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Image field in *special menu*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: special_menu.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Item field in *special menu*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: special_menu.item[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	item: prismic.GroupField<Simplify<SpecialMenuDocumentDataItemItem>>;
}

/**
 * special menu document from Prismic
 *
 * - **API ID**: `special_menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SpecialMenuDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<SpecialMenuDocumentData>,
	'special_menu',
	Lang
>;

export type AllDocumentTypes =
	| BeerMenuDocument
	| CocktailMenuDocument
	| DietaryBadgesDocument
	| ErrorPageDocument
	| FlavourStylesDocument
	| FoodMenuDocument
	| FooterDocument
	| FormerrorsDocument
	| NavDocument
	| OpeningHoursDocument
	| PageDocument
	| SettingsDocument
	| SpecialMenuDocument;

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
	/**
	 * Section Id field in *About → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.default.primary.section_id
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	section_id: prismic.KeyTextField;

	/**
	 * Title field in *About → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *About → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.default.primary.desciption
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	desciption: prismic.KeyTextField;

	/**
	 * Logo field in *About → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.default.primary.logo
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<AboutSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSlice = prismic.SharedSlice<'about', AboutSliceVariation>;

/**
 * Item in *Banner → Default → Primary → Slide*
 */
export interface BannerSliceDefaultPrimarySlideItem {
	/**
	 * Hero Image field in *Banner → Default → Primary → Slide*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner.default.primary.slide[].hero_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	hero_image: prismic.ImageField<never>;
}

/**
 * Item in *Banner → Default → Primary → CTA*
 */
export interface BannerSliceDefaultPrimaryCtaItem {
	/**
	 * Label field in *Banner → Default → Primary → CTA*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Lorem ipsum
	 * - **API ID Path**: banner.default.primary.cta[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * Link field in *Banner → Default → Primary → CTA*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner.default.primary.cta[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Primary content in *Banner → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
	/**
	 * Slide field in *Banner → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner.default.primary.slide[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	slide: prismic.GroupField<Simplify<BannerSliceDefaultPrimarySlideItem>>;

	/**
	 * CTA field in *Banner → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner.default.primary.cta[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	cta: prismic.GroupField<Simplify<BannerSliceDefaultPrimaryCtaItem>>;

	/**
	 * Title field in *Banner → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Slogan field in *Banner → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner.default.primary.slogan
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	slogan: prismic.KeyTextField;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<BannerSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<'banner', BannerSliceVariation>;

/**
 * Item in *Contact → Default → Primary → Phone Input*
 */
export interface ContactSliceDefaultPrimaryPhoneInputItem {
	/**
	 * Label field in *Contact → Default → Primary → Phone Input*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.phone_input[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * Icon field in *Contact → Default → Primary → Phone Input*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.phone_input[].icon
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	icon: prismic.KeyTextField;
}

/**
 * Item in *Contact → Default → Primary → Adresse Input*
 */
export interface ContactSliceDefaultPrimaryAdresseInputItem {
	/**
	 * Label field in *Contact → Default → Primary → Adresse Input*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.adresse_input[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * Icon field in *Contact → Default → Primary → Adresse Input*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.adresse_input[].icon
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	icon: prismic.KeyTextField;
}

/**
 * Item in *Contact → Default → Primary → Email Input*
 */
export interface ContactSliceDefaultPrimaryEmailInputItem {
	/**
	 * Label field in *Contact → Default → Primary → Email Input*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.email_input[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * Icon field in *Contact → Default → Primary → Email Input*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.email_input[].icon
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	icon: prismic.KeyTextField;
}

/**
 * Item in *Contact → Default → Primary → Form*
 */
export interface ContactSliceDefaultPrimaryFormInputsItem {
	/**
	 * Name field in *Contact → Default → Primary → Form*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.form_inputs[].name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;

	/**
	 * Email field in *Contact → Default → Primary → Form*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.form_inputs[].email
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	email: prismic.KeyTextField;

	/**
	 * Phone field in *Contact → Default → Primary → Form*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.form_inputs[].phone
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	phone: prismic.KeyTextField;

	/**
	 * Subject field in *Contact → Default → Primary → Form*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.form_inputs[].subject
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subject: prismic.KeyTextField;

	/**
	 * Subject Option 1 field in *Contact → Default → Primary → Form*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.form_inputs[].subject_option_1
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subject_option_1: prismic.KeyTextField;

	/**
	 * Subject Option 2 field in *Contact → Default → Primary → Form*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.form_inputs[].subject_option_2
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subject_option_2: prismic.KeyTextField;

	/**
	 * Reservationtype field in *Contact → Default → Primary → Form*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.form_inputs[].reservationtype
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	reservationtype: prismic.KeyTextField;

	/**
	 * Reservationtype Option 1 field in *Contact → Default → Primary → Form*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.form_inputs[].reservationtype_option_1
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	reservationtype_option_1: prismic.KeyTextField;

	/**
	 * Reservationtype Option 2 field in *Contact → Default → Primary → Form*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.form_inputs[].reservationtype_option_2
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	reservationtype_option_2: prismic.KeyTextField;

	/**
	 * NbPerson field in *Contact → Default → Primary → Form*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.form_inputs[].nbperson
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	nbperson: prismic.KeyTextField;

	/**
	 * Message field in *Contact → Default → Primary → Form*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.form_inputs[].message
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	message: prismic.KeyTextField;

	/**
	 * Send Button field in *Contact → Default → Primary → Form*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.form_inputs[].send_button
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	send_button: prismic.KeyTextField;
}

/**
 * Item in *Contact → Default → Primary → Form Sent*
 */
export interface ContactSliceDefaultPrimaryFormSentItem {
	/**
	 * error field in *Contact → Default → Primary → Form Sent*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.form_sent[].error
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	error: prismic.KeyTextField;

	/**
	 * success field in *Contact → Default → Primary → Form Sent*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.form_sent[].success
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	success: prismic.KeyTextField;

	/**
	 * button field in *Contact → Default → Primary → Form Sent*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.form_sent[].button
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button: prismic.KeyTextField;

	/**
	 * try again field in *Contact → Default → Primary → Form Sent*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.form_sent[].try_again
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	try_again: prismic.KeyTextField;
}

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
	/**
	 * Section Id field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.section_id
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	section_id: prismic.KeyTextField;

	/**
	 * Location field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: GeoPoint
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.location
	 * - **Documentation**: https://prismic.io/docs/field#geopoint
	 */
	location: prismic.GeoPointField;

	/**
	 * Title field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Disclaimer field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.disclaimer
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	disclaimer: prismic.KeyTextField;

	/**
	 * Phone Input field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.phone_input[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	phone_input: prismic.GroupField<Simplify<ContactSliceDefaultPrimaryPhoneInputItem>>;

	/**
	 * Adresse Input field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.adresse_input[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	adresse_input: prismic.GroupField<Simplify<ContactSliceDefaultPrimaryAdresseInputItem>>;

	/**
	 * Email Input field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.email_input[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	email_input: prismic.GroupField<Simplify<ContactSliceDefaultPrimaryEmailInputItem>>;

	/**
	 * Form field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.form_inputs[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	form_inputs: prismic.GroupField<Simplify<ContactSliceDefaultPrimaryFormInputsItem>>;

	/**
	 * Form Sent field in *Contact → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.default.primary.form_sent[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	form_sent: prismic.GroupField<Simplify<ContactSliceDefaultPrimaryFormSentItem>>;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ContactSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<'contact', ContactSliceVariation>;

/**
 * Primary content in *Events → Default → Primary*
 */
export interface EventsSliceDefaultPrimary {
	/**
	 * Title field in *Events → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: events.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Google field in *Events → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: events.default.primary.google
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	google: prismic.KeyTextField;

	/**
	 * Google Text field in *Events → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: events.default.primary.google_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	google_text: prismic.KeyTextField;

	/**
	 * Instagram field in *Events → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: events.default.primary.instagram
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	instagram: prismic.KeyTextField;

	/**
	 * Instagram Text field in *Events → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: events.default.primary.instagram_texte
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	instagram_texte: prismic.KeyTextField;

	/**
	 * Facebook field in *Events → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: events.default.primary.facebook
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	facebook: prismic.KeyTextField;

	/**
	 * Facebook Text field in *Events → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: events.default.primary.facebook_texte
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	facebook_texte: prismic.KeyTextField;
}

/**
 * Default variation for Events Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<EventsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Events*
 */
type EventsSliceVariation = EventsSliceDefault;

/**
 * Events Shared Slice
 *
 * - **API ID**: `events`
 * - **Description**: Events
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventsSlice = prismic.SharedSlice<'events', EventsSliceVariation>;

/**
 * Item in *Gallery → Default → Primary → Thumbnail*
 */
export interface GallerySliceDefaultPrimaryThumbnailItem {
	/**
	 * Image field in *Gallery → Default → Primary → Thumbnail*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery.default.primary.thumbnail[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Primary content in *Gallery → Default → Primary*
 */
export interface GallerySliceDefaultPrimary {
	/**
	 * Section Id field in *Gallery → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery.default.primary.section_id
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	section_id: prismic.KeyTextField;

	/**
	 * Title field in *Gallery → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Image field in *Gallery → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Thumbnail field in *Gallery → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery.default.primary.thumbnail[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	thumbnail: prismic.GroupField<Simplify<GallerySliceDefaultPrimaryThumbnailItem>>;
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<GallerySliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: Gallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySlice = prismic.SharedSlice<'gallery', GallerySliceVariation>;

/**
 * Default variation for Menu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuSliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	never
>;

/**
 * Slice variation for *Menu*
 */
type MenuSliceVariation = MenuSliceDefault;

/**
 * Menu Shared Slice
 *
 * - **API ID**: `menu`
 * - **Description**: Menu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuSlice = prismic.SharedSlice<'menu', MenuSliceVariation>;

/**
 * Primary content in *MenuBanner → Default → Primary*
 */
export interface MenuBannerSliceDefaultPrimary {
	/**
	 * Image field in *MenuBanner → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menu_banner.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Title field in *MenuBanner → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menu_banner.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *MenuBanner → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menu_banner.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
}

/**
 * Default variation for MenuBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuBannerSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<MenuBannerSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *MenuBanner*
 */
type MenuBannerSliceVariation = MenuBannerSliceDefault;

/**
 * MenuBanner Shared Slice
 *
 * - **API ID**: `menu_banner`
 * - **Description**: MenuBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuBannerSlice = prismic.SharedSlice<'menu_banner', MenuBannerSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			BeerMenuDocument,
			BeerMenuDocumentData,
			BeerMenuDocumentDataItemItem,
			CocktailMenuDocument,
			CocktailMenuDocumentData,
			CocktailMenuDocumentDataItemItem,
			DietaryBadgesDocument,
			DietaryBadgesDocumentData,
			ErrorPageDocument,
			ErrorPageDocumentData,
			FlavourStylesDocument,
			FlavourStylesDocumentData,
			FoodMenuDocument,
			FoodMenuDocumentData,
			FoodMenuDocumentDataItemItem,
			FooterDocument,
			FooterDocumentData,
			FormerrorsDocument,
			FormerrorsDocumentData,
			FormerrorsDocumentDataNameItem,
			FormerrorsDocumentDataEmailItem,
			FormerrorsDocumentDataPhoneItem,
			FormerrorsDocumentDataSubjectItem,
			FormerrorsDocumentDataMessageItem,
			FormerrorsDocumentDataDateItem,
			FormerrorsDocumentDataReservationtypeItem,
			FormerrorsDocumentDataNumberofpeopleItem,
			NavDocument,
			NavDocumentData,
			NavDocumentDataLinkItem,
			OpeningHoursDocument,
			OpeningHoursDocumentData,
			OpeningHoursDocumentDataDayItem,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			SettingsDocument,
			SettingsDocumentData,
			SettingsDocumentDataSocialMediaItem,
			SettingsDocumentDataCcEmailsItem,
			SettingsDocumentDataOpeningHoursItem,
			SpecialMenuDocument,
			SpecialMenuDocumentData,
			SpecialMenuDocumentDataItemItem,
			AllDocumentTypes,
			AboutSlice,
			AboutSliceDefaultPrimary,
			AboutSliceVariation,
			AboutSliceDefault,
			BannerSlice,
			BannerSliceDefaultPrimarySlideItem,
			BannerSliceDefaultPrimaryCtaItem,
			BannerSliceDefaultPrimary,
			BannerSliceVariation,
			BannerSliceDefault,
			ContactSlice,
			ContactSliceDefaultPrimaryPhoneInputItem,
			ContactSliceDefaultPrimaryAdresseInputItem,
			ContactSliceDefaultPrimaryEmailInputItem,
			ContactSliceDefaultPrimaryFormInputsItem,
			ContactSliceDefaultPrimaryFormSentItem,
			ContactSliceDefaultPrimary,
			ContactSliceVariation,
			ContactSliceDefault,
			EventsSlice,
			EventsSliceDefaultPrimary,
			EventsSliceVariation,
			EventsSliceDefault,
			GallerySlice,
			GallerySliceDefaultPrimaryThumbnailItem,
			GallerySliceDefaultPrimary,
			GallerySliceVariation,
			GallerySliceDefault,
			MenuSlice,
			MenuSliceVariation,
			MenuSliceDefault,
			MenuBannerSlice,
			MenuBannerSliceDefaultPrimary,
			MenuBannerSliceVariation,
			MenuBannerSliceDefault
		};
	}
}
